parameters:
    profile_directory: '%kernel.project_dir%/public/uploads'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_phone_number: '%env(TWILIO_PHONE_NUMBER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Override FOSUserBundle SecurityController
    fos_user.security.controller:
        class: App\Controller\SecurityController
        arguments: ['@security.authentication_utils']

    # Custom AuthenticationSuccessHandler service definition
    App\Security\AuthenticationSuccessHandler:
        arguments:
            - '@router'

    # Custom LoginFormAuthenticator for reCAPTCHA validation
    App\Security\LoginFormAuthenticator:
        arguments:
            - '@router'

    # Symfony Finder service
    Symfony\Component\Finder\Finder: ~

    # Social User Provider for HWIOAuthBundle
    app.social_user_provider:
        class: App\Security\SocialUserProvider
        arguments: ['@App\Repository\UserRepository']

    # OAuth Success Listener for custom redirects after social login
    app.oauth_success_listener:
        class: App\EventListener\OAuthSuccessListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }