
# This file is the entry point to configure your own services.  
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    profile_directory: '%kernel.project_dir%/public/uploads'

    voiture_images_directory: '%kernel.project_dir%/public/uploads/voitures'



services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    # Custom AuthenticationSuccessHandler service definition
    App\Security\AuthenticationSuccessHandler:
        arguments:
            $router: '@router'

   
    # config/services.yaml

    App\Service\NotificationService:
        arguments:
            $pusherKey: 'a57746eaf2c89e4593e9'
            $pusherSecret: 'dacc11e11452323c90b9'
            $pusherAppId: '1980718'
            $pusherCluster: 'eu'
     # Symfony Finder service (already configured)
    Symfony\Component\Finder\Finder: ~
    App\Service\StripeService:
        arguments:
            $privateKey: 'sk_test_51QwhI1H4NaQY1zAhv8ezh7HtXMNMTfgMKcGiZhkUjzguNONfGJJXC0XyAgBmEf60fx3Afuq7C1rPa1yZl8AqaaM900gbo7OuIk'
            $currency: 'eur'