parameters:
    pusher.app_id: '%env(PUSHER_APP_ID)%'
    pusher.key: '%env(PUSHER_KEY)%'
    pusher.secret: '%env(PUSHER_SECRET)%'
    pusher.cluster: '%env(PUSHER_CLUSTER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Finder\Finder: ~

    Pusher\Pusher:
        arguments:
            $auth_key: '%pusher.key%'
            $secret: '%pusher.secret%'
            $app_id: '%pusher.app_id%'
            $options:
                cluster: '%pusher.cluster%'
                useTLS: true