parameters:
    env(STRIPE_SECRET_KEY): '%env(STRIPE_SECRET_KEY)%'
    env(STRIPE_CURRENCY): '%env(STRIPE_CURRENCY)%'

services:


    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    Symfony\Component\Finder\Finder: ~

    # 👉 Cette configuration spécifique doit venir à la fin
    App\Service\StripeService:
        arguments:
            $privateKey: 'sk_test_51QwhI1H4NaQY1zAhv8ezh7HtXMNMTfgMKcGiZhkUjzguNONfGJJXC0XyAgBmEf60fx3Afuq7C1rPa1yZl8AqaaM900gbo7OuIk'
            $currency: 'eur'

